from enum import Enum

class ErrorCodes(Enum):
    # Chybové návratové kódy
    ERR_MISSING_PARAM = 10
    ERR_FILE_OPEN = 11
    ERR_FILE_WRITE = 12

    ERR_INVALID_XML_FORMAT = 31
    ERR_INVALID_XML_STRUCTURE = 32

    ERR_SEMANTIC_ERROR = 52
    ERR_OPERAND_TYPE_ERROR = 53
    ERR_UNDEFINED_VARIABLE = 54
    ERR_FRAME_NOT_FOUND = 55
    ERR_MISSING_VALUE = 56
    ERR_INVALID_OPERAND_VALUE = 57
    ERR_STRING_ERROR = 58

    ERR_INTERNAL = 99
