#!/bin/bash

# Check if the "parser.php" file exists
if [ -f "parser.php" ]; then
  # Delete the "parser.php" file if it exists
  rm parser.php
fi

# Create an empty file to store the concatenated content
echo "<?php" > parser.php
echo "" >> parser.php

# Loop through all files in the current directory
for file in *; do
  # Check if the file is a regular file and not the "genproj" or "parser.php" file
  if [ -f "$file" ] && [ "$file" != "genproj" ] && [ "$file" != "parser.php" ]; then
    # Ignore the first line of each file and append the rest to the parser.php file
    sed '1d' "$file" >> parser.php
  fi
done
